#!/usr/bin/env python3
"""Multi-file CImporter: process multiple .c files into a Lean 4 module set.

Processes multiple translation units and emits:
  - Generated/<Project>/Types.lean: shared struct/enum definitions
  - Generated/<Project>/<File>.lean: per-file function bodies
  - Each per-file module imports the common Types module

Usage:
    python3 CImporter/multi_import.py --project MyProject \
        test/clang_json/FileA.json test/clang_json/FileB.json \
        -o Generated/MyProject

This tool is in the TCB. See CImporter/README.md for the trust model.
"""

import argparse
import logging
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from CImporter.ast_parser import load_ast, parse_translation_unit, TranslationUnit, FuncInfo
from CImporter.lean_emitter import emit_lean, LeanEmitter
from CImporter.c_types import StructDef, get_struct_defs, clear_struct_defs

log = logging.getLogger("CImporter.multi")


def collect_shared_types(translation_units: list[tuple[str, TranslationUnit]]) -> tuple[list[StructDef], dict[str, int]]:
    """Collect struct definitions and enum constants shared across TUs.

    Returns (shared_structs, shared_enum_constants).
    Structs are deduplicated by name (first definition wins).
    """
    seen_structs: dict[str, StructDef] = {}
    all_enum_constants: dict[str, int] = {}

    for name, tu in translation_units:
        for sdef in tu.structs:
            if sdef.name not in seen_structs:
                seen_structs[sdef.name] = sdef
                log.info("Shared struct from %s: %s (size=%d)", name, sdef.name, sdef.total_size)
            else:
                log.debug("Duplicate struct %s from %s (using first definition)", sdef.name, name)
        for enum_info in tu.enums:
            for ec in enum_info.constants:
                if ec.name not in all_enum_constants:
                    all_enum_constants[ec.name] = ec.value

    return list(seen_structs.values()), all_enum_constants


def emit_types_module(project: str, structs: list[StructDef],
                      enum_constants: dict[str, int]) -> str:
    """Emit the shared Types module with struct definitions and enum constants."""
    lines = []
    lines.append(f"-- Generated by CImporter multi_import. Do not edit.")
    lines.append(f"-- Shared types for project: {project}")
    lines.append("")
    lines.append("import Clift.CSemantics")
    lines.append("")
    lines.append(f"set_option maxHeartbeats 400000")
    lines.append(f"set_option linter.unusedVariables false")
    lines.append("")
    lines.append(f"namespace {project}.Types")
    lines.append("")

    # Emit enum constants
    if enum_constants:
        lines.append("/-! # Enum constants -/")
        lines.append("")
        for name, value in sorted(enum_constants.items()):
            lines.append(f"def {name} : UInt32 := {value}")
        lines.append("")

    # Emit struct definitions using a temporary LeanEmitter for the struct emission logic
    # We create a minimal TranslationUnit just for the struct emission
    if structs:
        lines.append("/-! # Shared struct definitions -/")
        lines.append("")
        # Use the existing emitter infrastructure for struct emission
        from CImporter.ast_parser import TranslationUnit as TU
        dummy_tu = TU(functions=[], structs=structs)
        emitter = LeanEmitter(dummy_tu, f"{project}.Types")
        for sdef in structs:
            emitter._emit_struct(sdef)
            emitter._w()
        lines.extend(emitter.lines)

    lines.append("")
    lines.append(f"end {project}.Types")
    lines.append("")
    return "\n".join(lines) + "\n"


def emit_file_module(project: str, file_name: str, tu: TranslationUnit,
                     all_tus: list[tuple[str, TranslationUnit]]) -> str:
    """Emit a per-file module that imports the shared Types module.

    External function calls (functions not defined in this TU) are
    still emitted as .call "name" in the ProcEnv -- the assumption is
    that the user will compose ProcEnvs at the proof level.
    """
    # Override the struct list to empty (structs come from Types module)
    # but keep the TU's functions and other data
    emitter = LeanEmitter(tu, f"{project}.{file_name}")
    lines = []
    lines.append(f"-- Generated by CImporter multi_import. Do not edit.")
    lines.append(f"-- Source file: {file_name}")
    lines.append(f"-- Project: {project}")
    lines.append("")
    lines.append("import Clift.CSemantics")
    lines.append(f"import Generated.{project}.Types")
    lines.append("")
    lines.append(f"set_option maxHeartbeats 400000")
    lines.append(f"set_option linter.unusedVariables false")
    lines.append("")
    lines.append(f"open {project}.Types")
    lines.append("")
    lines.append(f"namespace {project}.{file_name}")
    lines.append("")

    # Emit locals (including from this file's functions)
    emitter._emit_locals()
    lines.extend(emitter.lines)
    emitter.lines = []

    emitter._emit_state_abbrev()
    lines.extend(emitter.lines)
    emitter.lines = []
    lines.append("")

    # Emit function bodies
    for func in tu.functions:
        emitter._emit_function(func)
        lines.extend(emitter.lines)
        emitter.lines = []
        lines.append("")

    # Emit proc env
    emitter._emit_proc_env()
    lines.extend(emitter.lines)
    emitter.lines = []

    lines.append("")
    lines.append(f"end {project}.{file_name}")
    lines.append("")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(
        description="Multi-file CImporter: process multiple .c files into Lean 4 modules.",
    )
    parser.add_argument(
        "inputs",
        nargs="+",
        help="Paths to clang JSON AST files",
    )
    parser.add_argument(
        "--project",
        required=True,
        help="Project name (used as Lean namespace prefix)",
    )
    parser.add_argument(
        "-o", "--output-dir",
        required=True,
        help="Output directory for generated .lean files (e.g. Generated/MyProject)",
    )
    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Enable verbose logging",
    )
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(name)s: %(levelname)s: %(message)s",
    )

    # Parse all translation units
    translation_units = []
    for json_path in args.inputs:
        file_name = os.path.splitext(os.path.basename(json_path))[0]
        log.info("Parsing %s (module: %s)", json_path, file_name)
        ast = load_ast(json_path)
        tu = parse_translation_unit(ast)
        translation_units.append((file_name, tu))
        log.info("  %d functions, %d structs", len(tu.functions), len(tu.structs))

    # Collect shared types
    shared_structs, shared_enums = collect_shared_types(translation_units)
    log.info("Shared: %d structs, %d enum constants", len(shared_structs), len(shared_enums))

    # Emit Types module
    os.makedirs(args.output_dir, exist_ok=True)
    types_code = emit_types_module(args.project, shared_structs, shared_enums)
    types_path = os.path.join(args.output_dir, "Types.lean")
    with open(types_path, 'w') as f:
        f.write(types_code)
    log.info("Wrote %s (%d lines)", types_path, types_code.count('\n'))

    # Emit per-file modules
    for file_name, tu in translation_units:
        file_code = emit_file_module(args.project, file_name, tu, translation_units)
        file_path = os.path.join(args.output_dir, f"{file_name}.lean")
        with open(file_path, 'w') as f:
            f.write(file_code)
        log.info("Wrote %s (%d lines)", file_path, file_code.count('\n'))


if __name__ == "__main__":
    main()
