"""Tests for CImporter.proof_engine.gen_projections."""

import pytest
from CImporter.proof_engine.gen_projections import (
    parse_generated_file,
    generate_projections,
    _parse_locals_struct,
    _parse_basic_lambdas,
    _parse_with_assignments,
)


SWAP_SOURCE = """\
-- Generated by CImporter from clang JSON AST. Do not edit.
-- Source module: Swap

import Clift.CSemantics

set_option maxHeartbeats 400000
set_option linter.unusedVariables false

namespace Swap

structure Locals where
  a : Ptr UInt32
  b : Ptr UInt32
  t : UInt32
  deriving Repr, DecidableEq, Inhabited

abbrev ProgramState := CState Locals

def swap_body : CSimpl ProgramState :=
  .catch
    (
      .seq
        (
          .guard (fun s => heapPtrValid s.globals.rawHeap s.locals.a)
            (
              .basic (fun s => { s with locals := { s.locals with t := (hVal s.globals.rawHeap s.locals.a) } })
            )
        )
        (
          .seq
            (
              .guard (fun s => heapPtrValid s.globals.rawHeap s.locals.a)
                (
                  .guard (fun s => heapPtrValid s.globals.rawHeap s.locals.b)
                    (
                      .basic (fun s => { s with globals := { s.globals with rawHeap := heapUpdate s.globals.rawHeap s.locals.a (hVal s.globals.rawHeap s.locals.b) } })
                    )
                )
            )
            (
              .guard (fun s => heapPtrValid s.globals.rawHeap s.locals.b)
                (
                  .basic (fun s => { s with globals := { s.globals with rawHeap := heapUpdate s.globals.rawHeap s.locals.b s.locals.t } })
                )
            )
        )
    )
    .skip

def procEnv : ProcEnv ProgramState :=
  ProcEnv.insert (ProcEnv.empty) "swap" swap_body

end Swap
"""


class TestParseLocals:
    def test_swap_locals(self):
        fields = _parse_locals_struct(SWAP_SOURCE)
        assert len(fields) == 3
        assert fields[0].name == "a"
        assert fields[0].type == "Ptr UInt32"
        assert fields[1].name == "b"
        assert fields[2].name == "t"
        assert fields[2].type == "UInt32"


class TestParseBasicLambdas:
    def test_swap_finds_three_lambdas(self):
        fields = _parse_locals_struct(SWAP_SOURCE)
        lambdas = _parse_basic_lambdas(SWAP_SOURCE, fields)
        assert len(lambdas) == 3

    def test_swap_step1_is_locals_update(self):
        fields = _parse_locals_struct(SWAP_SOURCE)
        lambdas = _parse_basic_lambdas(SWAP_SOURCE, fields)
        step1 = lambdas[0]
        assert step1.func_name == "swap"
        assert step1.step_index == 1
        assert step1.update_kind == "locals"
        assert "t" in step1.locals_updates
        assert step1.locals_updates["t"] == "(hVal s.globals.rawHeap s.locals.a)"

    def test_swap_step2_is_globals_update(self):
        fields = _parse_locals_struct(SWAP_SOURCE)
        lambdas = _parse_basic_lambdas(SWAP_SOURCE, fields)
        step2 = lambdas[1]
        assert step2.func_name == "swap"
        assert step2.step_index == 2
        assert step2.update_kind == "globals"
        assert "heapUpdate" in step2.globals_rawheap_expr

    def test_swap_step3_is_globals_update(self):
        fields = _parse_locals_struct(SWAP_SOURCE)
        lambdas = _parse_basic_lambdas(SWAP_SOURCE, fields)
        step3 = lambdas[2]
        assert step3.update_kind == "globals"
        assert "s.locals.t" in step3.globals_rawheap_expr


class TestParseWithAssignments:
    def test_single_field(self):
        result = _parse_with_assignments("ret__val := 1", "s")
        assert result == {"ret__val": "1"}

    def test_nested_expression(self):
        result = _parse_with_assignments(
            "t := (hVal s.globals.rawHeap s.locals.a)", "s"
        )
        assert result == {"t": "(hVal s.globals.rawHeap s.locals.a)"}

    def test_multiple_fields(self):
        result = _parse_with_assignments(
            "rb := s.locals.src, out_val := s.locals.scratch", "s"
        )
        assert result == {
            "rb": "s.locals.src",
            "out_val": "s.locals.scratch",
        }


class TestGenerateProjections:
    def test_swap_output_has_namespace(self):
        module = parse_generated_file(SWAP_SOURCE)
        output = generate_projections(module)
        assert "namespace Swap.Projections" in output
        assert "end Swap.Projections" in output

    def test_swap_output_has_step_functions(self):
        module = parse_generated_file(SWAP_SOURCE)
        output = generate_projections(module)
        assert "noncomputable def swap_step1" in output
        assert "noncomputable def swap_step2" in output
        assert "noncomputable def swap_step3" in output

    def test_swap_output_has_locals_eq(self):
        module = parse_generated_file(SWAP_SOURCE)
        output = generate_projections(module)
        assert "swap_step1_locals_eq" in output

    def test_swap_output_has_field_projections(self):
        module = parse_generated_file(SWAP_SOURCE)
        output = generate_projections(module)
        assert "swap_step1_a" in output
        assert "swap_step1_b" in output
        assert "swap_step1_t" in output

    def test_swap_output_has_funext(self):
        module = parse_generated_file(SWAP_SOURCE)
        output = generate_projections(module)
        assert "swap_step1_funext" in output
        assert "swap_step2_funext" in output
        assert "swap_step3_funext" in output

    def test_swap_output_has_simp_attrs(self):
        module = parse_generated_file(SWAP_SOURCE)
        output = generate_projections(module)
        assert "@[simp] theorem swap_step1_globals" in output
        assert "@[simp] theorem swap_step1_a" in output

    def test_swap_output_has_irreducible_for_heap(self):
        module = parse_generated_file(SWAP_SOURCE)
        output = generate_projections(module)
        assert "attribute [local irreducible] hVal" in output
        assert "attribute [local irreducible] heapUpdate" in output

    def test_func_prefix_filter(self):
        module = parse_generated_file(SWAP_SOURCE)
        # Use a prefix that won't match
        output = generate_projections(module, func_prefix="nonexistent")
        assert "noncomputable def" not in output

    def test_anonymous_constructor_in_locals_update(self):
        module = parse_generated_file(SWAP_SOURCE)
        output = generate_projections(module)
        # step1 is locals update, should use ⟨s.globals, ⟨...⟩⟩ pattern
        assert "⟨s.globals, ⟨s.locals.a, s.locals.b," in output

    def test_anonymous_constructor_in_globals_update(self):
        module = parse_generated_file(SWAP_SOURCE)
        output = generate_projections(module)
        # step2 is globals update, should use ⟨⟨heap_expr⟩, s.locals⟩ pattern
        assert "⟨⟨heapUpdate" in output
        assert ", s.locals⟩" in output
