-- Task 0144: Independent kernel check — axiom audit
--
-- Run #print axioms on all key theorems to verify:
-- 1. Each depends only on propext, Quot.sound, Classical.choice (standard Lean axioms)
-- 2. No theorem depends on sorryAx
-- 3. Document the trusted base: Lean 4 kernel + CImporter
--
-- This is defense-in-depth. Even if lake build says success, we verify
-- the kernel actually checked everything and no sorry leaked through.

import Examples.GcdEndToEnd
import Examples.SwapProof
import Examples.SoundnessCheck
import Examples.TerminationProofs
import Examples.RingBufferExtProof
import Examples.MultiCallProof

/-! # Axiom Audit: systematic check of all key theorems

    Expected axioms (standard Lean 4, acceptable):
    - propext : (a ↔ b) → a = b
    - Quot.sound : r a b → Quot.mk r a = Quot.mk r b
    - Classical.choice : Nonempty α → α

    UNACCEPTABLE axiom:
    - sorryAx : (α : Sort u) → Bool → α  (indicates an unproven sorry)

    If any theorem below shows sorryAx, it means a proof has a sorry
    and is NOT actually proven. This would be a critical finding. -/

/-! ## Category 1: Core semantics (CSemantics) -/

-- Terminates_implies_Exec: the key link
#print axioms Terminates_implies_Exec

-- cHoare rules
#print axioms cHoare_skip
#print axioms cHoare_basic
#print axioms cHoare_seq
#print axioms cHoare_cond
#print axioms cHoare_guard
#print axioms cHoare_throw
#print axioms cHoare_catch
#print axioms cHoare_consequence
#print axioms cHoare_dynCom

-- cHoareTotal
#print axioms cHoareTotal_iff
#print axioms cHoareTotal_implies_exists_outcome

/-! ## Category 2: MonadLib (NondetM, Hoare triples) -/

#print axioms validHoare_pure
#print axioms totalHoare_pure

/-! ## Category 3: L1 Hoare rules -/

#print axioms L1_guard_not_failed
#print axioms L1_guard_results
#print axioms L1_guard_modify_result

/-! ## Category 4: FuncSpec framework -/

#print axioms FuncSpec.call_spec
#print axioms FuncSpec.call_spec_exact
#print axioms L1_hoare_call_spec
#print axioms L1_hoare_dynCom

/-! ## Category 5: L1corres proofs for ring_buffer_ext (40 functions)
    These are generated by the clift pipeline and should be sorry-free -/

#print axioms RingBufferExt.l1_rb_init_body_corres
#print axioms RingBufferExt.l1_rb_push_body_corres
#print axioms RingBufferExt.l1_rb_pop_body_corres
#print axioms RingBufferExt.l1_rb_peek_body_corres
#print axioms RingBufferExt.l1_rb_size_body_corres
#print axioms RingBufferExt.l1_rb_is_empty_body_corres
#print axioms RingBufferExt.l1_rb_is_full_body_corres
#print axioms RingBufferExt.l1_rb_clear_body_corres
#print axioms RingBufferExt.l1_rb_count_nodes_body_corres
#print axioms RingBufferExt.l1_rb_contains_body_corres
#print axioms RingBufferExt.l1_rb_peek_back_body_corres
#print axioms RingBufferExt.l1_rb_capacity_body_corres
#print axioms RingBufferExt.l1_rb_remaining_body_corres
#print axioms RingBufferExt.l1_rb_stats_total_ops_body_corres
#print axioms RingBufferExt.l1_rb_stats_init_body_corres
#print axioms RingBufferExt.l1_rb_stats_update_push_body_corres
#print axioms RingBufferExt.l1_rb_stats_update_pop_body_corres
#print axioms RingBufferExt.l1_rb_stats_reset_body_corres
#print axioms RingBufferExt.l1_rb_iter_init_body_corres
#print axioms RingBufferExt.l1_rb_iter_has_next_body_corres
#print axioms RingBufferExt.l1_rb_iter_next_body_corres
#print axioms RingBufferExt.l1_rb_iter_skip_body_corres
#print axioms RingBufferExt.l1_rb_increment_all_body_corres
#print axioms RingBufferExt.l1_rb_sum_body_corres
#print axioms RingBufferExt.l1_rb_find_index_body_corres
#print axioms RingBufferExt.l1_rb_nth_body_corres
#print axioms RingBufferExt.l1_rb_remove_first_match_body_corres
#print axioms RingBufferExt.l1_rb_swap_front_back_body_corres
#print axioms RingBufferExt.l1_rb_min_body_corres
#print axioms RingBufferExt.l1_rb_max_body_corres
#print axioms RingBufferExt.l1_rb_replace_all_body_corres
#print axioms RingBufferExt.l1_rb_reverse_body_corres
#print axioms RingBufferExt.l1_rb_count_above_body_corres
#print axioms RingBufferExt.l1_rb_count_at_or_below_body_corres
#print axioms RingBufferExt.l1_rb_fill_body_corres
#print axioms RingBufferExt.l1_rb_equal_body_corres
-- Call-containing functions
#print axioms RingBufferExt.l1_rb_check_integrity_body_corres
#print axioms RingBufferExt.l1_rb_push_if_not_full_body_corres
#print axioms RingBufferExt.l1_rb_pop_if_not_empty_body_corres
#print axioms RingBufferExt.l1_rb_drain_to_body_corres

/-! ## Category 6: Termination proofs (sorry-free expected) -/

#print axioms rb_capacity_terminates
#print axioms rb_size_terminates
#print axioms rb_remaining_terminates
#print axioms rb_is_empty_terminates
#print axioms rb_is_full_terminates
#print axioms rb_stats_total_ops_terminates
#print axioms rb_iter_has_next_terminates

/-! ## Category 7: Soundness checks -/

#print axioms select_empty_validHoare
#print axioms select_empty_not_totalHoare
#print axioms skip_terminates
#print axioms while_false_terminates

/-! ## Category 8: Concrete proofs (GCD, swap, etc.) -/

-- GCD (auto-generated via clift in GcdEndToEnd.lean)
#print axioms Gcd.l1_gcd_body_corres

-- Swap (auto-generated via clift in SwapProof.lean)
#print axioms Swap.l1_swap_body_corres

-- MultiCall
#print axioms MultiCall.l1_add_body_corres
#print axioms MultiCall.l1_max_val_body_corres

/-! ## Category 9: Abstract spec properties (RBExtRefinement) -/

#print axioms RBExtSpec.queue_fifo
#print axioms RBExtSpec.queue_push_pop_empty
#print axioms RBExtSpec.queue_size_push
#print axioms RBExtSpec.queue_inv_push
#print axioms RBExtSpec.queue_inv_pop

/-! # Trusted Computing Base (TCB) documentation

    Our proofs are only as strong as the weakest link in the TCB:

    1. **Lean 4 kernel** (trusted): Type-checks all proof terms. We trust it
       is correct. Lean has independent kernel checkers (lean4checker) that
       provide additional assurance.

    2. **CImporter** (trusted): Python script that translates clang JSON AST
       to CSimpl Lean terms. If this mistranslates, proofs are about the wrong
       program. Mitigated by snapshot tests and differential testing.

    3. **Clang** (trusted): We trust clang's JSON AST is a faithful representation
       of the C source. Pinned via Nix flake to a specific LLVM version.

    4. **Standard Lean axioms** (trusted):
       - propext: propositional extensionality
       - Quot.sound: quotient soundness
       - Classical.choice: axiom of choice
       These are the standard axioms of Lean 4's type theory.

    NOT in the TCB (verified by proofs):
    - Exec semantics (rules are definitions, proved correct by cHoare)
    - L1corres lifting (proved for each function)
    - FuncSpecs (proved by validHoare)
    - Abstract specs (proved directly in Lean)
    - Refinement chain (composition of corres, FuncSpec, AbstractSpec)

    ## sorryAx audit expectation

    Theorems that SHOULD show sorryAx (because they contain sorry):
    - All 25 validHoare proofs in RBExtFuncSpecs.lean
    - All 7 totalHoare proofs in RBExtFuncSpecs.lean
    - 3 refinement proofs in RBExtRefinement.lean

    Theorems that MUST NOT show sorryAx:
    - All 40 L1corres proofs
    - All 7 Terminates proofs
    - All cHoare rules
    - All soundness check theorems
    - Terminates_implies_Exec
    - All abstract spec properties
-/
