/-!
# Proof Integrity Audit

Deterministic checks for proof chain integrity:
1. All validHoare theorems use auto-generated L1 bodies (from `clift`)
2. No circular specs (postcondition not baked into definition)
3. No sorryAx in key theorems
4. Proof chains back to actual CSimpl (from CImporter)

Run: `lake build Examples.ProofIntegrityAudit`
If any `#guard` fails, the audit found an issue.
-/

import Examples.GcdEndToEnd

/-! ## 1. GCD end-to-end chain audit

The proof must:
- Use auto-generated Gcd.l1_gcd_body (from clift, not hand-written)
- Chain through L1corres to CSimpl
- Have no sorry axioms
-/

-- Verify the auto-generated body exists and is used
#check @Gcd.l1_gcd_body        -- auto-generated by clift
#check @Gcd.l1_gcd_body_corres -- auto-generated L1corres proof
#check @gcd_correct_nat_e2e    -- the end-to-end theorem

-- Verify no sorry axioms in the proof chain
#print axioms gcd_correct_nat_e2e
-- Expected: propext, Quot.sound only (NO sorryAx)

/-! ## 2. Axiom audit for all key theorems

Any theorem showing `sorryAx` has an unproven sorry in its dependency chain.
-/

-- Core library theorems (must be sorry-free)
#print axioms L1corres_cHoare_bridge
#print axioms @L1_hoare_while

/-! ## 3. Documentation

### What this audit catches:
- sorryAx in proof chains (via #print axioms)
- Missing auto-generation (would fail to compile if Gcd.l1_gcd_body doesn't exist)

### What this audit does NOT catch (use `just audit` for these):
- Hand-written L1 bodies in other files (grep-based check)
- Tautological postconditions (grep for validHoare_weaken_trivial_post)
- Circular NondetM definitions (grep for results := fun.*∃)
- Proofs against fused/manual bodies (grep for satisfiedBy.*manual)

### Full audit: run both
```
just audit     # deterministic grep checks
lake build Examples.ProofIntegrityAudit  # Lean kernel checks
```
-/
