-- Generated by CImporter from clang JSON AST. Do not edit.
-- Source module: Gcd
-- Regenerate with: just import test/c_sources/gcd.c Gcd

import Clift.CSemantics

set_option maxHeartbeats 400000

namespace Gcd

/-- Local variables (merged from all functions). -/
structure Locals where
  a : UInt32
  b : UInt32
  ret__val : UInt32
  t : UInt32
  deriving Repr, DecidableEq, Inhabited

/-- Program state combining globals and locals. -/
abbrev ProgramState := CState Locals

/-- CSimpl body for gcd(). -/
def gcd_body : CSimpl ProgramState :=
  .catch
    (
      .seq
        (
          .while (fun s => decide (s.locals.b ≠ 0))
            (
              .seq
                (
                  .basic (fun s => { s with locals := { s.locals with t := s.locals.b } })
                )
                (
                  .seq
                    (
                      .basic (fun s => { s with locals := { s.locals with b := (s.locals.a % s.locals.b) } })
                    )
                    (
                      .basic (fun s => { s with locals := { s.locals with a := s.locals.t } })
                    )
                )
            )
        )
        (
          .seq (.basic (fun s => { s with locals := { s.locals with ret__val := s.locals.a } })) .throw
        )
    )
    .skip

/-- Procedure environment mapping function names to bodies. -/
def procEnv : ProcEnv ProgramState :=
  ProcEnv.insert (ProcEnv.empty) "gcd" gcd_body

end Gcd
