-- Generated by CImporter from clang JSON AST. Do not edit.
-- Source module: Max
-- Regenerate with: just import test/c_sources/max.c Max

import Clift.CSemantics

set_option maxHeartbeats 400000
set_option linter.unusedVariables false

namespace Max

/-- Local variables (merged from all functions).
    NOTE: Locals use Inhabited default (zero-init). See task-0060. -/
structure Locals where
  a : UInt32
  b : UInt32
  ret__val : UInt32
  deriving Repr, DecidableEq, Inhabited

/-- Program state combining globals and locals. -/
abbrev ProgramState := CState Locals

/-- CSimpl body for max(). -/
def max_body : CSimpl ProgramState :=
  .catch
    (
      .seq (.basic (fun s => { s with locals := { s.locals with ret__val := (if decide (s.locals.a > s.locals.b) then s.locals.a else s.locals.b) } })) .throw
    )
    .skip

/-- Procedure environment mapping function names to bodies. -/
def procEnv : ProcEnv ProgramState :=
  ProcEnv.insert (ProcEnv.empty) "max" max_body

end Max
